# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7
  - pypy2.7-6.0
  - pypy3.5-6.0
env:
  - COVERALLS_PARALLEL=true

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis coveralls

# Command to run tests, e.g. python setup.py test
script:
  - echo TRAVIS_PYTHON_VERSION:$TRAVIS_PYTHON_VERSION
  - tox

after_success: coveralls
notifications:
  webhooks:
    - "https://coveralls.io/webhook"  # Tell coveralls that this build has finished. Necessary when using PARALLEL mode
